apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ENVIRONMENT}-${REPOSITORY}
  namespace: ${NAMESPACE}
  labels:
    app: ${ENVIRONMENT}-${REPOSITORY}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${ENVIRONMENT}-${REPOSITORY}
  template:
    metadata:
      labels:
        app: ${ENVIRONMENT}-${REPOSITORY}
    spec:
      containers:
      - name: container-1
        image: ${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "${ENVIRONMENT}"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ${ENVIRONMENT}-${REPOSITORY}
  namespace: ${NAMESPACE}
  labels:
    app: ${ENVIRONMENT}-${REPOSITORY}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: ${NODEPORT} # yaml-language-server: $schema=ignore
    protocol: TCP
    name: http
  selector:
    app: ${ENVIRONMENT}-${REPOSITORY}